<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [FaxGate-users] Problem Versand nach eingang in queue
   </TITLE>
   <LINK REL="Index" HREF="http://lists.berlios.de/pipermail/faxgate-users/2007-March/index.html" >
   <LINK REL="made" HREF="mailto:faxgate-users%40lists.berlios.de?Subject=Re%3A%20%5BFaxGate-users%5D%20Problem%20Versand%20nach%20eingang%20in%20queue&In-Reply-To=%3C45E732A6.5090200%40starkmedien.de%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   
   
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[FaxGate-users] Problem Versand nach eingang in queue</H1>
    <B>Thomas Stark</B> 
    <A HREF="mailto:faxgate-users%40lists.berlios.de?Subject=Re%3A%20%5BFaxGate-users%5D%20Problem%20Versand%20nach%20eingang%20in%20queue&In-Reply-To=%3C45E732A6.5090200%40starkmedien.de%3E"
       TITLE="[FaxGate-users] Problem Versand nach eingang in queue">info at starkmedien.de
       </A><BR>
    <I>Thu Mar  1 21:08:06 CET 2007</I>
    <P><UL>
        
        
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#10">[ date ]</a>
              <a href="thread.html#10">[ thread ]</a>
              <a href="subject.html#10">[ subject ]</a>
              <a href="author.html#10">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Hallo liebes Forum,

ich habe ein Problem beim tats&#228;chlichen versenden von Faxen &#252;ber die
FaxGate-Schnittstelle.

Bisher war zum Faxempfang capusiute 0.4 installiert und hat faxe
entgegengenommen und per pdf-mail weiterversendet.

Ich m&#246;chte nun auch Faxe per Netzwerk-Drucker (Samba) verschicken. Es
ist so, dass Faxe auf den Drucker eingehen und in der queue liegen.
Jedoch bekomme ich folgende Fehlermeldungen aus der capisiute.error..


Thu Mar  1 20:36:58 2007 Pythonscript
/usr/lib/capisuite/idle.py,idle,0x81a58b8: A python error occured. See
traceback below.
Thu Mar  1 20:36:58 2007 Pythonscript
/usr/lib/capisuite/idle.py,idle,0x81a58b8: Python traceback: Traceback
(most recent call last):
Thu Mar  1 20:36:58 2007 Pythonscript
/usr/lib/capisuite/idle.py,idle,0x81a58b8: Python traceback:   File
&quot;/usr/lib/capisuite/idle.py&quot;, line 37, in idle
Thu Mar  1 20:36:58 2007 Pythonscript
/usr/lib/capisuite/idle.py,idle,0x81a58b8: Python traceback:
userdata=pwd.getpwnam(user)
Thu Mar  1 20:36:58 2007 Pythonscript
/usr/lib/capisuite/idle.py,idle,0x81a58b8: Python traceback: KeyError:
'getpwnam(): name not found'

Wo es l&#228;uft:

OS: Suse 9.1
Capisiute-Version CapiSuite 0.5.cvs (c) by Gernot Hillier
&lt;<A HREF="https://lists.berlios.de/mailman/listinfo/faxgate-users">gernot at hillier.de</A>&gt;

Danke f&#252;r jede Hilfe,
Tom


</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	
	
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#10">[ date ]</a>
              <a href="thread.html#10">[ thread ]</a>
              <a href="subject.html#10">[ subject ]</a>
              <a href="author.html#10">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://lists.berlios.de/mailman/listinfo/faxgate-users">More information about the FaxGate-users
mailing list</a><br>
</body></html>
